/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicCard: typeof import('./src/components/BasicCard.vue')['default']
    BasicFooter: typeof import('./src/components/BasicFooter.vue')['default']
    CollectionNav: typeof import('./src/components/CollectionNav.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    MiniMothLogo: typeof import('./src/components/brand/MiniMothLogo.vue')['default']
    MothLogo: typeof import('./src/components/brand/MothLogo.vue')['default']
    MothWordmark: typeof import('./src/components/brand/MothWordmark.vue')['default']
    Portfolio: typeof import('./src/components/Portfolio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TiptapCodeBlock: typeof import('./src/components/TiptapCodeBlock.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    TiptapTest: typeof import('./src/components/TiptapTest.vue')['default']
    VuesticNavBar: typeof import('./src/components/VuesticNavBar.vue')['default']
  }
}
