/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMarkerSwitch: typeof import('./src/components/demos/map/AddMarkerSwitch.vue')['default']
    BasicCard: typeof import('./src/components/BasicCard.vue')['default']
    BasicFooter: typeof import('./src/components/BasicFooter.vue')['default']
    CollectionGrid: typeof import('./src/components/CollectionGrid.vue')['default']
    CollectionNav: typeof import('./src/components/CollectionNav.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    CurrentLocation: typeof import('./src/components/demos/map/currentLocation.vue')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    FloatingEditorMenu: typeof import('./src/components/editor/FloatingEditorMenu.vue')['default']
    GoogleAutocomplete: typeof import('./src/components/demos/map/GoogleAutocomplete.vue')['default']
    MiniMothLogo: typeof import('./src/components/brand/MiniMothLogo.vue')['default']
    MothLogo: typeof import('./src/components/brand/MothLogo.vue')['default']
    MothWordmark: typeof import('./src/components/brand/MothWordmark.vue')['default']
    PromptModal: typeof import('./src/components/input/PromptModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlashCommands: typeof import('./src/components/editor/SlashCommands.vue')['default']
    StackableSheet: typeof import('./src/components/layout/StackableSheet.vue')['default']
    TiptapCodeBlock: typeof import('./src/components/editor/TiptapCodeBlock.vue')['default']
    TiptapEditor: typeof import('./src/components/editor/TiptapEditor.vue')['default']
    TiptapTest: typeof import('./src/components/editor/TiptapTest.vue')['default']
    TriangleShape: typeof import('./src/components/shapes/TriangleShape.vue')['default']
    VuesticNavBar: typeof import('./src/components/VuesticNavBar.vue')['default']
  }
}
