/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    MiniMothLogo: typeof import('./src/components/brand/MiniMothLogo.vue')['default']
    MothLogo: typeof import('./src/components/brand/MothLogo.vue')['default']
    MothWordmark: typeof import('./src/components/brand/MothWordmark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VuesticDarkModeSwitch: typeof import('./src/components/VuesticDarkModeSwitch.vue')['default']
    VuesticNavBar: typeof import('./src/components/VuesticNavBar.vue')['default']
  }
}
