-- Theme seed data for sf/sl design system
-- Copy into the custom migration generated by `pnpm migrate:custom:api`.

INSERT INTO themes (slug, name, activation_class, is_root) VALUES
	('root', 'Root', NULL, 1),
	('dark', 'Dark', 'theme-dark', 0),
	('pink', 'Pink', 'theme-pink', 0);

-- ─── Root theme: complete token set ──────────────────────────────────────

INSERT INTO theme_tokens (theme_slug, name, value, kind) VALUES
	-- Text sizes
	('root', '--sf-text-xs',   '0.75rem',  'length'),
	('root', '--sf-text-sm',   '0.875rem', 'length'),
	('root', '--sf-text-base', '1rem',     'length'),
	('root', '--sf-text-lg',   '1.125rem', 'length'),
	('root', '--sf-text-xl',   '1.25rem',  'length'),
	('root', '--sf-text-2xl',  '1.5rem',   'length'),
	('root', '--sf-text-3xl',  '1.875rem', 'length'),
	('root', '--sf-text-4xl',  '2.25rem',  'length'),
	('root', '--sf-text-5xl',  '3rem',     'length'),
	('root', '--sf-text-6xl',  '3.75rem',  'length'),
	('root', '--sf-text-7xl',  '4.5rem',   'length'),
	('root', '--sf-text-8xl',  '6rem',     'length'),
	('root', '--sf-text-9xl',  '8rem',     'length'),

	-- Spacing
	('root', '--sf-spacing-none', '0px',     'length'),
	('root', '--sf-spacing-xs',   '0.5rem',  'length'),
	('root', '--sf-spacing-sm',   '0.75rem', 'length'),
	('root', '--sf-spacing-md',   '1.25rem', 'length'),
	('root', '--sf-spacing-lg',   '2rem',    'length'),
	('root', '--sf-spacing-xl',   '3rem',    'length'),

	-- Leading
	('root', '--sf-leading-none',    '1',     'number'),
	('root', '--sf-leading-tight',   '1.25',  'number'),
	('root', '--sf-leading-snug',    '1.375', 'number'),
	('root', '--sf-leading-normal',  '1.5',   'number'),
	('root', '--sf-leading-relaxed', '1.625', 'number'),
	('root', '--sf-leading-loose',   '2',     'number'),

	-- Tracking
	('root', '--sf-tracking-tight',  '-0.025em', 'length'),
	('root', '--sf-tracking-normal', '0em',      'length'),
	('root', '--sf-tracking-wide',   '0.025em',  'length'),

	-- Shadow shapes (paired with --sf-shadow colour at use site)
	('root', '--sf-shadow-sm', '0 1px 4px',  'shadow-shape'),
	('root', '--sf-shadow-md', '0 2px 8px',  'shadow-shape'),
	('root', '--sf-shadow-lg', '0 4px 16px', 'shadow-shape'),
	('root', '--sf-shadow-xl', '0 8px 24px', 'shadow-shape'),

	-- Shadow opacity (theme-level character; one value per theme, not a range)
	('root', '--sf-shadow-opacity', '0.12', 'number'),

	-- Container breakpoints
	('root', '--sf-breakpoint-xs', '380px', 'length'),
	('root', '--sf-breakpoint-sm', '640px', 'length'),
	('root', '--sf-breakpoint-md', '768px', 'length'),

	-- Primary palette (renumbered from 100..900)
	('root', '--sf-primary-1', '209 250 229', 'color-triplet'),
	('root', '--sf-primary-2', '167 243 208', 'color-triplet'),
	('root', '--sf-primary-3', '110 231 183', 'color-triplet'),
	('root', '--sf-primary-4', '52 211 153',  'color-triplet'),
	('root', '--sf-primary-5', '16 185 129',  'color-triplet'),
	('root', '--sf-primary-6', '5 150 105',   'color-triplet'),
	('root', '--sf-primary-7', '4 120 87',    'color-triplet'),
	('root', '--sf-primary-8', '6 95 70',     'color-triplet'),
	('root', '--sf-primary-9', '4 78 56',     'color-triplet'),

	-- Surface palette (0..9, surface-0 = canvas)
	('root', '--sf-surface-0', '255 255 255', 'color-triplet'),
	('root', '--sf-surface-1', '244 244 245', 'color-triplet'),
	('root', '--sf-surface-2', '228 228 231', 'color-triplet'),
	('root', '--sf-surface-3', '212 212 216', 'color-triplet'),
	('root', '--sf-surface-4', '161 161 170', 'color-triplet'),
	('root', '--sf-surface-5', '113 113 122', 'color-triplet'),
	('root', '--sf-surface-6', '82 82 91',    'color-triplet'),
	('root', '--sf-surface-7', '63 63 70',    'color-triplet'),
	('root', '--sf-surface-8', '39 39 42',    'color-triplet'),
	('root', '--sf-surface-9', '24 24 27',    'color-triplet'),

	-- Alpha (1..9, theme-controlled values)
	('root', '--sf-alpha-1', '0.1', 'number'),
	('root', '--sf-alpha-2', '0.2', 'number'),
	('root', '--sf-alpha-3', '0.3', 'number'),
	('root', '--sf-alpha-4', '0.4', 'number'),
	('root', '--sf-alpha-5', '0.5', 'number'),
	('root', '--sf-alpha-6', '0.6', 'number'),
	('root', '--sf-alpha-7', '0.7', 'number'),
	('root', '--sf-alpha-8', '0.8', 'number'),
	('root', '--sf-alpha-9', '0.9', 'number'),

	-- Font weight
	('root', '--sf-weight-1', '400', 'number'),
	('root', '--sf-weight-2', '500', 'number'),
	('root', '--sf-weight-3', '600', 'number'),
	('root', '--sf-weight-4', '700', 'number'),

	-- Radius
	('root', '--sf-radius-0', '0px',  'length'),
	('root', '--sf-radius-1', '4px',  'length'),
	('root', '--sf-radius-2', '8px',  'length'),
	('root', '--sf-radius-3', '16px', 'length'),

	-- Font families (1, 2, mono — slot 3 reserved)
	('root', '--sf-font-1',    '"Source Sans Pro", Inter, system-ui, sans-serif', 'text'),
	('root', '--sf-font-2',    '"Lora", Georgia, serif',                          'text'),
	('root', '--sf-font-mono', '"Source Code Pro", "Fira Code", monospace',       'text'),

	-- Semantic tokens
	('root', '--sf-fg_primary',   '38 40 36',            'color-triplet'),
	('root', '--sf-fg_inverted',  '255 255 255',         'color-triplet'),
	('root', '--sf-primary',      'var(--sf-primary-5)', 'color-triplet'),
	('root', '--sf-border_color', '222 229 242',         'color-triplet'),
	('root', '--sf-shadow',       '0 0 0',               'color-triplet');

-- ─── Dark theme overrides ────────────────────────────────────────────────

INSERT INTO theme_tokens (theme_slug, name, value, kind) VALUES
	('dark', '--sf-fg_primary',   '241 241 241',         'color-triplet'),
	('dark', '--sf-fg_inverted',  '11 18 26',            'color-triplet'),
	('dark', '--sf-border_color', '61 76 88',            'color-triplet'),
	('dark', '--sf-primary',      'var(--sf-primary-4)', 'color-triplet');

-- ─── Pink theme overrides ────────────────────────────────────────────────

INSERT INTO theme_tokens (theme_slug, name, value, kind) VALUES
	-- Primary palette
	('pink', '--sf-primary-1', '255 204 230', 'color-triplet'),
	('pink', '--sf-primary-2', '255 179 218', 'color-triplet'),
	('pink', '--sf-primary-3', '255 153 204', 'color-triplet'),
	('pink', '--sf-primary-4', '255 128 191', 'color-triplet'),
	('pink', '--sf-primary-5', '255 102 178', 'color-triplet'),
	('pink', '--sf-primary-6', '255 77 166',  'color-triplet'),
	('pink', '--sf-primary-7', '255 51 153',  'color-triplet'),
	('pink', '--sf-primary-8', '255 26 140',  'color-triplet'),
	('pink', '--sf-primary-9', '255 0 128',   'color-triplet'),

	-- Surface palette
	('pink', '--sf-surface-0', '255 240 245', 'color-triplet'),
	('pink', '--sf-surface-1', '255 220 235', 'color-triplet'),
	('pink', '--sf-surface-2', '255 210 230', 'color-triplet'),
	('pink', '--sf-surface-3', '255 200 225', 'color-triplet'),
	('pink', '--sf-surface-4', '255 180 215', 'color-triplet'),
	('pink', '--sf-surface-5', '255 160 205', 'color-triplet'),
	('pink', '--sf-surface-6', '255 140 195', 'color-triplet'),
	('pink', '--sf-surface-7', '255 120 185', 'color-triplet'),
	('pink', '--sf-surface-8', '255 100 175', 'color-triplet'),
	('pink', '--sf-surface-9', '255 80 165',  'color-triplet'),

	-- Semantic
	('pink', '--sf-fg_primary',  '102 0 51',    'color-triplet'),
	('pink', '--sf-fg_inverted', '255 230 240', 'color-triplet');

-- ─── Rich classes — vocabulary ───────────────────────────────────────────
-- Only bundles, variants, states live here. Single-property semantic /
-- utility / palette classes are auto-derived by the generator from
-- theme_tokens + property-mapping rules.

INSERT INTO class_vocabulary (name, kind, layer, description) VALUES
	('sf-depth-0',   'bundle', 'sf-bundle', 'Canvas / page — bottommost surface'),
	('sf-depth-1',   'bundle', 'sf-bundle', 'One level above canvas — cards, wells'),
	('sf-depth-2',   'bundle', 'sf-bundle', 'Further raised — dropdowns, popovers'),
	('sf-depth-3',   'bundle', 'sf-bundle', 'Topmost — modals'),
	('sf-heading-1', 'bundle', 'sf-bundle', 'Most prominent heading'),
	('sf-heading-2', 'bundle', 'sf-bundle', 'Secondary heading'),
	('sf-heading-3', 'bundle', 'sf-bundle', 'Tertiary heading');

-- ─── Rich classes — root property assignments ───────────────────────────
-- Themes can override per (theme_slug, class_name, css_property); when a
-- theme just shifts the underlying token, no override row is needed —
-- the bundle inherits the new value through the token cascade.

INSERT INTO class_properties (theme_slug, class_name, css_property, value) VALUES
	('root', 'sf-depth-0',   'background',  'rgb(var(--sf-surface-0))'),
	('root', 'sf-depth-1',   'background',  'rgb(var(--sf-surface-1))'),
	('root', 'sf-depth-2',   'background',  'rgb(var(--sf-surface-2))'),
	('root', 'sf-depth-3',   'background',  'rgb(var(--sf-surface-3))'),
	('root', 'sf-heading-1', 'font-size',   'var(--sf-text-4xl)'),
	('root', 'sf-heading-1', 'line-height', 'var(--sf-leading-tight)'),
	('root', 'sf-heading-2', 'font-size',   'var(--sf-text-2xl)'),
	('root', 'sf-heading-2', 'line-height', 'var(--sf-leading-snug)'),
	('root', 'sf-heading-3', 'font-size',   'var(--sf-text-xl)'),
	('root', 'sf-heading-3', 'line-height', 'var(--sf-leading-snug)');
