import fs from 'fs'
import postcss from 'postcss'
import safe from 'postcss-safe-parser'

type Variables = Record<string, string>

const extractVars = (selector: string, cssAst: postcss.Result<postcss.Root>) => {
	const variables: Variables = {}
	cssAst.root.walkRules(selector, (rule) => {
		rule.walkDecls((decl) => {
			if (decl.prop.startsWith('--')) {
				variables[decl.prop] = decl.value
			}
		})
	})
	return variables
}

// Function to resolve the value of a variable
const resolveVar = (variables: Variables, varName: string, lookupVariables: Variables) => {
	let value = variables[varName]
	while (value && value.startsWith('var(')) {
		const referencedVar = value.match(/var\((--[^)]+)\)/)?.[1] || ''
		value = lookupVariables[referencedVar] || referencedVar
	}
	return value
}

// Resolve all variables in an object
const resolveAllVars = (variables: Variables, lookupVariables: Variables) => {
	const resolvedVars: Variables = {}
	for (const key of Object.keys(variables)) {
		const resolvedVar = resolveVar(variables, key, lookupVariables)
		if (resolvedVar) resolvedVars[key] = resolvedVar
	}
	return resolvedVars
}

const run = async (cssFilePaths: string | string[], saveLocation: string) => {
	const paths = Array.isArray(cssFilePaths) ? cssFilePaths : [cssFilePaths]

	// Merge vars across files; later files override earlier on conflict (last write wins).
	const merged = { root: {} as Variables, dark: {} as Variables, pink: {} as Variables }
	for (const cssFilePath of paths) {
		const cssString = await fs.readFileSync(cssFilePath)
		const cssAst = await postcss().process(cssString, {
			from: cssFilePath,
			parser: safe,
		})
		Object.assign(merged.root, extractVars(':root', cssAst))
		Object.assign(merged.dark, extractVars('.theme-dark', cssAst))
		Object.assign(merged.pink, extractVars('.theme-pink', cssAst))
	}

	const jsonContent = {
		root: resolveAllVars(merged.root, merged.root),
		dark: resolveAllVars(merged.dark, { ...merged.root, ...merged.dark }),
		pink: resolveAllVars(merged.pink, { ...merged.root, ...merged.pink }),
	}

	fs.writeFileSync(
		saveLocation + '.js',
		'// This file is generated by extractCssVars.ts'
			+ '\n\n'
			+ 'export default '
			+ JSON.stringify(jsonContent, null, 2),
	)
}

export default run
