-- Sample collections and pages for trying the site locally. Safe to run again.
-- From api/: npx wrangler d1 execute somefreq-db --local --file sample-data/collections.sql
-- Pages marked unpublished (published = 0) only show for admins.

INSERT OR IGNORE INTO site_tags (name, slug, published, created_at, updated_at) VALUES
  ('Branding', 'branding', 1, unixepoch(), unixepoch()),
  ('Software Development', 'software-development', 1, unixepoch(), unixepoch());

INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-moth-co', 'Moth & Co', 'https://picsum.photos/seed/sample-moth-co/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Moth & Co"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-moth-co' AND t.slug = 'branding';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-harbour-coffee', 'Harbour Coffee', 'https://picsum.photos/seed/sample-harbour-coffee/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Harbour Coffee"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-harbour-coffee' AND t.slug = 'branding';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-northfield-books', 'Northfield Books', NULL, 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Northfield Books"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-northfield-books' AND t.slug = 'branding';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-kiln-studio', 'Kiln Studio', 'https://picsum.photos/seed/sample-kiln-studio/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Kiln Studio"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-kiln-studio' AND t.slug = 'branding';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-draft-identity', 'Draft identity', NULL, 0, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Draft identity"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-draft-identity' AND t.slug = 'branding';

INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-shop-redesign', 'Shop redesign', 'https://picsum.photos/seed/sample-shop-redesign/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Shop redesign"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-shop-redesign' AND t.slug = 'software-development';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-booking-app', 'Booking app', 'https://picsum.photos/seed/sample-booking-app/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Booking app"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-booking-app' AND t.slug = 'software-development';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-charity-site', 'Charity site', NULL, 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Charity site"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-charity-site' AND t.slug = 'software-development';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-recipe-blog', 'Recipe blog', 'https://picsum.photos/seed/sample-recipe-blog/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Recipe blog"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-recipe-blog' AND t.slug = 'software-development';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-portfolio-template', 'Portfolio template', 'https://picsum.photos/seed/sample-portfolio-template/800/600', 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Portfolio template"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-portfolio-template' AND t.slug = 'software-development';
INSERT OR IGNORE INTO site_pages (slug, name, image_url, published, content_json, created_at, updated_at) VALUES ('sample-dashboard', 'Dashboard', NULL, 1, '{"type": "doc", "content": [{"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Dashboard"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "A short introduction to this project and what it set out to do."}]}, {"type": "heading", "attrs": {"level": 2}, "content": [{"type": "text", "text": "The brief"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The client wanted something that felt calm and confident, and worked just as well on a phone as on a big screen."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "We started with a few rough directions, tested them with real content, and kept the one that read best at every size."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "The finished work shipped on time and has been in use since."}]}]}', unixepoch(), unixepoch());
INSERT OR IGNORE INTO site_page_tags (page_id, tag_id) SELECT p.page_id, t.tag_id FROM site_pages p, site_tags t WHERE p.slug = 'sample-dashboard' AND t.slug = 'software-development';
