import { integer, primaryKey, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const themes = sqliteTable('themes', {
	slug: text('slug', { length: 64 }).primaryKey(),
	name: text('name', { length: 256 }).notNull(),
	activationClass: text('activation_class', { length: 64 }),
	isRoot: integer('is_root', { mode: 'boolean' }).notNull().default(false),
	createdAt: integer('created_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
	updatedAt: integer('updated_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
})

export const themeTokens = sqliteTable(
	'theme_tokens',
	{
		themeSlug: text('theme_slug', { length: 64 })
			.notNull()
			.references(() => themes.slug, { onDelete: 'cascade', onUpdate: 'cascade' }),
		name: text('name', { length: 128 }).notNull(),
		value: text('value', { length: 512 }).notNull(),
		kind: text('kind', { length: 32 }).notNull(),
	},
	(table) => ({
		pk: primaryKey({ columns: [table.themeSlug, table.name] }),
	}),
)

// Rich classes — bundles, variants, states.
// Semantic/utility/palette classes are auto-generated by the CSS generator
// from theme_tokens + property-mapping rules in code, not stored as rows.
export const classVocabulary = sqliteTable('class_vocabulary', {
	name: text('name', { length: 128 }).primaryKey(),
	kind: text('kind', { length: 32 }).notNull(),
	layer: text('layer', { length: 32 }).notNull(),
	description: text('description', { length: 512 }),
})

// Per-theme CSS property assignments for rich classes.
// Each property is one row — themes can set different property sets,
// and extraction vars (e.g. --sf-depth-1-background) fall out naturally.
export const classProperties = sqliteTable(
	'class_properties',
	{
		themeSlug: text('theme_slug', { length: 64 })
			.notNull()
			.references(() => themes.slug, { onDelete: 'cascade', onUpdate: 'cascade' }),
		className: text('class_name', { length: 128 })
			.notNull()
			.references(() => classVocabulary.name, { onDelete: 'cascade', onUpdate: 'cascade' }),
		cssProperty: text('css_property', { length: 64 }).notNull(),
		value: text('value', { length: 512 }).notNull(),
	},
	(table) => ({
		pk: primaryKey({ columns: [table.themeSlug, table.className, table.cssProperty] }),
	}),
)

export type Theme = typeof themes.$inferSelect
export type NewTheme = typeof themes.$inferInsert
export type ThemeToken = typeof themeTokens.$inferSelect
export type NewThemeToken = typeof themeTokens.$inferInsert
export type ClassVocabulary = typeof classVocabulary.$inferSelect
export type NewClassVocabulary = typeof classVocabulary.$inferInsert
export type ClassProperty = typeof classProperties.$inferSelect
export type NewClassProperty = typeof classProperties.$inferInsert
